version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=announcement_user
      - MARIADB_DATABASE=announcement_db
    ports:
      - 4306:3306
  laravel:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8080:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=announcement_user
      - DB_DATABASE=announcement_db
    volumes:
      - './backend:/app'
    depends_on:
      - mariadb
    command: bash -c "composer install && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"
  nextjs:
    image: node:latest
    working_dir: '/app'
    command: bash -c "npm install && npm run dev"
    volumes:
      - './frontend:/app'
    ports:
      - 4000:3000